# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lightning}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabriel Horner"]
  s.date = %q{2010-04-09}
  s.description = %q{Lightning is a commandline framework that changes how you use paths in your filesystem. Lightning generates shell functions which wrap any command with the ability to autocomplete and interpret paths simply by their basenames. With these functions you don't have to ever type the full path to any file for any command again.}
  s.email = %q{gabriel.horner@gmail.com}
  s.executables = ["lightning", "lightning-complete", "lightning-translate"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "bin/lightning",
     "bin/lightning-complete",
     "bin/lightning-translate",
     "lib/lightning.rb",
     "lib/lightning/bolt.rb",
     "lib/lightning/builder.rb",
     "lib/lightning/commands.rb",
     "lib/lightning/commands/bolt.rb",
     "lib/lightning/commands/core.rb",
     "lib/lightning/commands/function.rb",
     "lib/lightning/commands/shell_command.rb",
     "lib/lightning/commands_util.rb",
     "lib/lightning/completion.rb",
     "lib/lightning/completion_map.rb",
     "lib/lightning/config.rb",
     "lib/lightning/function.rb",
     "lib/lightning/generator.rb",
     "lib/lightning/generators.rb",
     "lib/lightning/generators/misc.rb",
     "lib/lightning/generators/ruby.rb",
     "lib/lightning/util.rb",
     "lib/lightning/version.rb",
     "test/bolt_test.rb",
     "test/builder_test.rb",
     "test/commands_test.rb",
     "test/completion_map_test.rb",
     "test/completion_test.rb",
     "test/config_test.rb",
     "test/function_test.rb",
     "test/generator_test.rb",
     "test/lightning.yml",
     "test/test_helper.rb"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://tagaholic.me/lightning}
  s.rdoc_options = ["--title", "Lightning 0.3.0 Documentation"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{tagaholic}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Lightning is a commandline framework that generates shell functions which wrap around commands to autocomplete and translate full paths by their basenames.}
  s.test_files = [
    "test/bolt_test.rb",
     "test/builder_test.rb",
     "test/commands_test.rb",
     "test/completion_map_test.rb",
     "test/completion_test.rb",
     "test/config_test.rb",
     "test/function_test.rb",
     "test/generator_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

