#This class generates shell scripts from a configuration.
class Lightning
  module Generator
    extend self

    HEADER = <<-INIT.gsub(/^\s+/,'')
    #### This file was generated by Lightning. ####
    #LBIN_PATH="$PWD/bin/" #only use for development
    LBIN_PATH=""
    INIT

    def run(generated_file=nil)
      Cli.read_config
      generated_file ||= Lightning.config[:generated_file]
      output = generate(Lightning.config[:shell], Lightning.commands.values)
      File.open(generated_file, 'w'){|f| f.write(output) }
      output
    end
          
    def generate(shell, *args)
      HEADER + "\n\n" + send("#{shell}_generator", *args)
    end
    
    def bash_generator(commands)
      commands.map do |e|
        <<-EOS
          #{'#' + e['description'] if e['description']}
          #{e['name']} () {
            #{e['shell_command']} `${LBIN_PATH}lightning-translate #{e['name']} $@`
          }
          complete -o default -C "${LBIN_PATH}lightning-complete #{e['name']}" #{e['name']}
        EOS
      end.join("\n").gsub(/^\s{6,10}/, '')
    end
  end
end
