class Lightning
  class Generator
    def self.generate(*args)
      shell = args.shift
      send("generate_#{shell}", *args)
    end
    
    def self.generate_bash(commands)
      body = <<-INIT
      #### This file was generated by Lightning. ####
      #Change this to match this project's base directory
      LBIN_PATH="/home/bozo/code/gems/lightning/bin"
      
      INIT
      commands.each do |e|
        body += <<-EOS
          
          ##{e['description'] if e['description']}
          #{e['name']} () {
            FULL_PATH=`$LBIN_PATH/lightning-full_path.rb #{e['path_key']} $@`
            CMD="#{e['map_to']} '$FULL_PATH#{e['post_path'] if e['post_path']}'#{' '+ e['add_to_command'] if e['add_to_command']}"
            if [ $1 == '#{Lightning::TEST_FLAG}' ]; then
              echo $CMD
            else
              $CMD
            fi
          }
          complete -o default -C "$LBIN_PATH/lightning-complete.rb #{e['path_key']}" #{e['name']}
        EOS
      end
      body.gsub(/^\s{6,10}/, '')
    end
  end
end
